[WIP]ユーザー管理機能の実装
hyugayuki/chat-space- pull request #4
Opened 2017-09-08 03:36 UTC by hyugayuki

# WHAT
ユーザー管理機能をdeviseを用いて実装する

# WHY
ログインユーザーのみがチャットを利用できるようにするため。

2017-09-09 04:41 UTC, offich requested changes
deviseの使いかたはOKです！
1点コメントさせていただいたので、お時間よろしいときに、見ていただけると幸いです。

2017-09-09 04:41 UTC, r-ume commented on db/schema.rb
> +    t.string   "username"
userモデルで、`validates :username, presence: true` していますが、ここは、`null: false` のオプションをつけていただけるとベターです。

2017-09-09 05:42 UTC, hyugayuki commented
以下、ユーザー編集機能の追加

2017-09-09 06:08 UTC, ryouzi commented on app/assets/stylesheets/user.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
こちら使っていないのであれば削除しましょう。

2017-09-09 06:08 UTC, ryouzi commented on db/migrate/20170908122230_add_username_to_users.rb
> +end
こちらのファイルはロールバックしてマイグレートしましたでしょうか？
schemaに変更がないので、気になって確認しました。

2017-09-09 06:25 UTC, hyugayuki commented on db/migrate/20170908122230_add_username_to_users.rb
> +end
ターミナル上では完了できています。
<img width="1440" alt="2017-09-09 15 24 34" src="https://user-images.githubusercontent.com/31532932/30237731-10089df8-9573-11e7-95df-c1e843c97952.png">

2017-09-09 07:09 UTC, miyagit commented on app/views/devise/mailer/confirmation_instructions.html.haml
> +%p
使わないファイルは消しましょう。

2017-09-09 07:09 UTC, miyagit commented on app/views/devise/mailer/email_changed.html.haml
> +%p
使わないファイルは消しましょう。

2017-09-09 07:09 UTC, miyagit commented on app/views/devise/mailer/password_change.html.haml
> +  Hello #{@resource.email}!
使わないファイルは消しましょう。

2017-09-09 07:09 UTC, miyagit commented on app/views/devise/mailer/reset_password_instructions.html.haml
> +%p Someone has requested a link to change your password. You can do this through the link below.
使わないファイルは消しましょう。

2017-09-09 07:09 UTC, miyagit commented on app/views/devise/mailer/unlock_instructions.html.haml
> +%p
使わないファイルは消しましょう。

2017-09-09 07:09 UTC, miyagit commented on app/views/devise/passwords/edit.html.haml
> +  = f.hidden_field :reset_password_token
使わないファイルは消しましょう。

2017-09-09 07:09 UTC, miyagit commented on app/views/devise/passwords/new.html.haml
> +    = f.label :email
使わないファイルは消しましょう。

2017-09-09 07:09 UTC, miyagit commented on app/views/devise/unlocks/new.html.haml
> +    = f.label :email
使わないファイルは消しましょう。

2017-09-11 03:42 UTC, hyugayuki commented
以下、ログイン・ログアウト機能の追加

2017-09-11 03:54 UTC, TOMARUMARU commented on app/controllers/messages_controller.rb
> +    @user_id = current_user.id
current_user.idを定義する必要がありますでしょうか？

2017-09-11 03:54 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +    current_user.update(user_params)
ユーザー情報編集の可否で処理を変えましょう。

2017-09-11 04:08 UTC, hyugayuki commented on app/controllers/messages_controller.rb
> +    @user_id = current_user.id
viewに設定した引数にそのままcurrent_user.idを書いて修正しました。

2017-09-11 05:53 UTC, TOMARUMARU commented on app/controllers/application_controller.rb
> +    '/users/sign_in'
prefixで指定しましょう！

2017-09-11 05:53 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +    if current_user.save(user_params)
saveで更新できていますでしょうか？

2017-09-11 07:39 UTC, hyugayuki commented
上記、フラッシュメッセージ機能

2017-09-11 08:44 UTC, merged