[wip]add function to send messages
hyugayuki/chat-space- pull request #7
Opened 2017-09-15 11:24 UTC by hyugayuki

# what
メッセージ送信機能の実装

# why
あらかじめ必要なユーザー・グループ管理機能ができたので、メッセージ送信機能を実装する。

2017-09-16 04:19 UTC, hyugayuki commented
・コントローラ、モデルを作成する
・ルーティングを設定する
・該当するアクションをコントローラに定義する
・メッセージ送信機能を実装する
を行いました。

2017-09-16 08:02 UTC, hyugayuki commented
・画像送信と保存に関する編集
・バリデーションの可否に応じたフラッシュメッセージの表示　を実装しました。

投稿メッセージの表示はまだです。

2017-09-16 08:10 UTC, fumihumi commented on app/controllers/messages_controller.rb
> +      redirect_to group_messages_path, alert: "メッセージを入力してください"
messageの送信失敗時はredirectを使わないようにしましょう！
redirectしてしまうとuserが入力したformデータが消えてしまうためです！

2017-09-16 08:10 UTC, fumihumi commented on app/controllers/messages_controller.rb
> +  def message_params
strongparameterにてcurrent_userのidをマージするのではなくmessage作成段階にてcurrent_userに紐づくmessageを作成するようにしましょう！

2017-09-16 08:10 UTC, fumihumi commented on app/models/message.rb
> +  validates :content, presence: true,  unless: :image?
message のバリデーションにはいくつかパターンがあります。
おそらく他の条件も必要になると思うので改めて考えてみましょう！

本番環境にて試してみると良いかとおもわれます！

2017-09-17 03:37 UTC, ken-nag reviewed
lgtm

2017-09-18 03:56 UTC, hyugayuki commented
投稿メッセージ表示機能です。

2017-09-18 04:00 UTC, ryouzi commented on app/controllers/messages_controller.rb
> +    @message = current_user.messages.build(message_params)
こちらはnewではいけないでしょうか、、、？

2017-09-18 04:31 UTC, hyugayuki commented on app/controllers/messages_controller.rb
> +    @message = current_user.messages.build(message_params)
以前はidが保存できるかできないかで違いがあったようですが
今は２つの違いはないという記事を見ました。newで統一して使っていきたいと思います。

2017-09-18 04:41 UTC, offich requested changes
お時間よろしいときに、見ていただければ、幸いです。

2017-09-18 04:41 UTC, r-ume commented on app/controllers/messages_controller.rb
> +  before_action :set_group, only: [:index, :create]
**GOOD**

before_actionで、抽象度をあげているのは、良いです！

2017-09-18 04:41 UTC, r-ume commented on app/models/message.rb
> +  validates :user_id, :group_id, null: false
こちらは、`null: false` より、 `presence: true` を書きましょう。

2017-09-18 04:41 UTC, r-ume commented on db/migrate/20170915113425_add_index_messages_content.rb
> +    add_index :messages, [:content, :image, :user_id, :group_id]
**THINK**
こちら、すべてにindexを貼ってしまうと、indexを貼るメリットがなくなるので、本当に必要なカラムにだけindexを貼るようにしましょう。

2017-09-18 04:41 UTC, r-ume commented on db/migrate/20170915112756_create_messages.rb
> +      t.string         :image
**MUST**
contentとimageにも、nullを許容しないようにしましょう。

2017-09-18 04:57 UTC, hyugayuki commented on db/migrate/20170915112756_create_messages.rb
> +      t.string         :image
文章or画像だけの投稿も許容するためにnullを許容しどちらもnullの場合はvalidationで弾くようにしていますが不十分でしょうか。

2017-09-18 05:06 UTC, hyugayuki commented on app/controllers/messages_controller.rb
> +  before_action :set_group, only: [:index, :create]
ありがとうございます！

2017-09-18 05:41 UTC, r-ume commented on db/migrate/20170915112756_create_messages.rb
> +      t.string         :image
おっしゃる通り、validationで弾くことができます。しかし、何らかの形でvalidationが通ってしまい、テーブルに保存されるかもしれないときのため、テーブルにもnullを許容しないようにという意図でお伝えいたしました。

2017-09-18 06:11 UTC, hyugayuki commented on db/migrate/20170915112756_create_messages.rb
> +      t.string         :image
　一つのテーブルにcontentとimageのカラムを作成しているので、片方のカラムの値が空のmessageレコードができてしまうケースは許容して保存したいのでこれで作成しました。
　メンターさんに質問させていただいたのですが、テーブルでもnullの検証を行う場合はimageとcontentのテーブルを分けることで検証を可能にすることができるから、本来はそれが望ましいが、今回は分けることをしないので大丈夫ではないかとのことです。
　実際にnullをつけると文章のみのメッセージは保存できませんでした。

2017-09-18 06:16 UTC, r-ume commented on db/migrate/20170915112756_create_messages.rb
> +      t.string         :image
> 一つのテーブルにcontentとimageのカラムを作成しているので、片方のカラムの値が空のmessageレコードができてしまうケースは許容して保存したいのでこれで作成しました。

大変失礼いたしました。お手数をおかけしてしまい、申し訳ないです！

2017-09-18 06:16 UTC, r-ume commented
LGTMです！

2017-09-19 00:16 UTC, hyugayuki commented
画像の表示、グループ名下最新メッセージの表示です。よろしくお願いします。

2017-09-19 02:16 UTC, TOMARUMARU reviewed
LGTMをもらっているようなのですが、まだこのブランチで作業をする場所があったということでしょうか？
また、6000を超えるファイルがプッシュされています。
gitignoreについて調べて、プッシュする必要のないファイルをプッシュしないようにしてください。

2017-09-19 03:33 UTC, hyugayuki commented
　見づらく申し訳有りません。少しずつプルリクエストを行いLGTMの後も同じブランチ内で作業を進めていました。次の作業からはマージし、ブランチを切りなおして進めるようにします。
　画像の表示、グループ名下最新メッセージの表示機能のレビューをお願いできますでしょうか。

2017-09-19 06:57 UTC, merged